ALTER TABLE clients ADD COLUMN IF NOT EXISTS alt_phone VARCHAR(20);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS gender VARCHAR(30);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS occupation VARCHAR(150);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS city VARCHAR(120);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS state VARCHAR(120);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS pin_code VARCHAR(6);

ALTER TABLE case_charge_items ADD COLUMN IF NOT EXISTS is_lawyer_fee BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE case_charge_items ADD COLUMN IF NOT EXISTS description VARCHAR(500);

ALTER TABLE case_documents ADD COLUMN IF NOT EXISTS description VARCHAR(2000);

ALTER TABLE payment_history ADD COLUMN IF NOT EXISTS payment_date DATE;
UPDATE payment_history
SET payment_date = COALESCE(payment_date, CAST(created_at AS DATE))
WHERE payment_date IS NULL;

ALTER TABLE cases ADD COLUMN IF NOT EXISTS judge_name VARCHAR(150);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS filing_date DATE;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS first_hearing_date DATE;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS next_hearing_date DATE;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS opponent_name VARCHAR(255);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS opponent_lawyer VARCHAR(150);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS case_description VARCHAR(2000);

ALTER TABLE cases DROP CONSTRAINT IF EXISTS cases_case_number_key;
CREATE UNIQUE INDEX IF NOT EXISTS idx_cases_case_number_org ON cases(organization_id, case_number);
