ALTER TABLE shared_tasks ADD COLUMN IF NOT EXISTS description VARCHAR(2000);
ALTER TABLE shared_tasks ADD COLUMN IF NOT EXISTS priority VARCHAR(100);
ALTER TABLE shared_tasks ADD COLUMN IF NOT EXISTS assigned_to VARCHAR(150);
ALTER TABLE shared_tasks ADD COLUMN IF NOT EXISTS assigned_by VARCHAR(150);
ALTER TABLE shared_tasks ADD COLUMN IF NOT EXISTS due_date TIMESTAMP;

CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    designation VARCHAR(100),
    contact_number VARCHAR(20) NOT NULL,
    email VARCHAR(150),
    organization VARCHAR(200),
    notes VARCHAR(500),
    created_by VARCHAR(150) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lobbying_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    purpose VARCHAR(200) NOT NULL,
    lobbying_date TIMESTAMP NOT NULL,
    status VARCHAR(50),
    notes VARCHAR(500),
    lobbying_officer VARCHAR(150),
    created_by VARCHAR(150),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS put_up_dates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    put_up_date_time TIMESTAMP NOT NULL,
    purpose VARCHAR(200) NOT NULL,
    court_name VARCHAR(150),
    judge_name VARCHAR(100),
    status VARCHAR(50),
    notes VARCHAR(500),
    lawyer_name VARCHAR(150),
    created_by VARCHAR(150) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO contacts (name, designation, contact_number, email, organization, notes, created_by)
SELECT 'Court Clerk Sharma', 'Court Clerk', '9000011111', 'clerk.sharma@example.com', 'Delhi High Court', 'Helps with filing status updates.', 'founder@lawoffice.com'
WHERE NOT EXISTS (SELECT 1 FROM contacts);

INSERT INTO lobbying_records (client_id, purpose, lobbying_date, status, notes, lobbying_officer, created_by)
SELECT 1, 'Compliance follow-up', TIMESTAMP '2026-04-08 15:00:00', 'Pending', 'Awaiting confirmation from authority office.', 'Adv. Mehra', 'founder@lawoffice.com'
WHERE NOT EXISTS (SELECT 1 FROM lobbying_records);

INSERT INTO put_up_dates (case_id, put_up_date_time, purpose, court_name, judge_name, status, notes, lawyer_name, created_by)
SELECT 1, TIMESTAMP '2026-04-12 11:30:00', 'Next hearing listing', 'Delhi High Court', 'Justice Verma', 'Scheduled', 'Prepare appearance note before listing.', 'Adv. Mehra', 'founder@lawoffice.com'
WHERE NOT EXISTS (SELECT 1 FROM put_up_dates);
