-- Migration: Add Multi-Tenancy support
-- This script creates the organizations table and links all core business data to it.

-- 1. Create Organizations table
CREATE TABLE IF NOT EXISTS organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Insert the Default Organization
-- We use a fixed ID 1 for the default organization to make migration easier.
INSERT INTO organizations (id, name, status) 
VALUES (1, 'Default Law Firm', 'ACTIVE');

-- 3. Add organization_id columns and constraints to existing tables
-- We set the default to 1 so existing data is automatically migrated.

ALTER TABLE local_users ADD COLUMN IF NOT EXISTS organization_id BIGINT DEFAULT 1 REFERENCES organizations(id);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS organization_id BIGINT DEFAULT 1 REFERENCES organizations(id);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS organization_id BIGINT DEFAULT 1 REFERENCES organizations(id);
ALTER TABLE shared_tasks ADD COLUMN IF NOT EXISTS organization_id BIGINT DEFAULT 1 REFERENCES organizations(id);
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS organization_id BIGINT DEFAULT 1 REFERENCES organizations(id);
ALTER TABLE lobbying_records ADD COLUMN IF NOT EXISTS organization_id BIGINT DEFAULT 1 REFERENCES organizations(id);
ALTER TABLE put_up_dates ADD COLUMN IF NOT EXISTS organization_id BIGINT DEFAULT 1 REFERENCES organizations(id);
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS organization_id BIGINT DEFAULT 1 REFERENCES organizations(id);

-- Optional: Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_users_org ON local_users(organization_id);
CREATE INDEX IF NOT EXISTS idx_clients_org ON clients(organization_id);
CREATE INDEX IF NOT EXISTS idx_cases_org ON cases(organization_id);
CREATE INDEX IF NOT EXISTS idx_tasks_org ON shared_tasks(organization_id);
